# Generated by Django 3.2.6 on 2021-10-05 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miércoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes')], default='Lu', max_length=2, verbose_name='Día de la semana')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('cp', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('nombreOS', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Obra Social')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección de la Obra Social')),
                ('disponible', models.BooleanField(verbose_name='Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_doc', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=150)),
                ('num_cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de CUIT/CUIL')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=50, verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='odontologia.localidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de la pieza dental')),
            ],
            options={
                'verbose_name_plural': 'Piezas dentales',
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de la prestación')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción de la prestación')),
                ('pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.piezadental')),
            ],
            options={
                'verbose_name_plural': 'Prestaciones',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de matrícula')),
                ('especialidad', models.CharField(max_length=150)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('medico_efector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.profesional')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=8, verbose_name='Contraseña')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_persona', to='odontologia.persona')),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoPrestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_tratamiento', to='odontologia.prestacion')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacionPzaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.piezadental')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_pzadental', to='odontologia.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('num_hc', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de historia clínica')),
                ('num_os', models.IntegerField(blank=True, null=True, verbose_name='Número de Obra Social')),
                ('titular', models.BooleanField(verbose_name='¿Titular?')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('nombre', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Nombre del establecimiento')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón social')),
                ('direccion', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=50, verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('web', models.CharField(max_length=200, verbose_name='Dirección Web')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidad_establecimiento', to='odontologia.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='odontologia.paciente')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora del turno')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.profesional')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='odontologia.paciente')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de alta')),
                ('tipo_factor_sangre', models.CharField(max_length=3, verbose_name='Tipo y factor de sangre')),
                ('antecedentes', models.CharField(max_length=1000)),
                ('medicacion', models.CharField(max_length=1000, verbose_name='Medicación')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.establecimiento')),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedicaTratamiento',
            fields=[
                ('fichamedica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='odontologia.fichamedica')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento')),
            ],
        ),
    ]
