# Generated by Django 3.2.6 on 2021-09-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de matrícula')),
                ('especialidad', models.CharField(max_length=150)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.persona')),
            ],
        ),
    ]
