# Generated by Django 3.2.6 on 2021-09-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0003_alter_persona_num_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del establecimiento')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón social')),
                ('direccion', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=50, verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('web', models.CharField(max_length=200, verbose_name='Dirección Web')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidad_establecimiento', to='odontologia.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('nombreOS', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='Obra Social')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección de la Obra Social')),
                ('disponible', models.BooleanField(verbose_name='Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la pieza dental')),
            ],
            options={
                'verbose_name_plural': 'Piezas dentales',
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la prestación')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción de la prestación')),
                ('pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.piezadental')),
            ],
            options={
                'verbose_name_plural': 'Prestaciones',
            },
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='titular_familiar',
            new_name='titular',
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del turno')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.paciente')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('medico_efector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.profesional')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de alta')),
                ('tipo_factor_sangre', models.CharField(max_length=3, verbose_name='Tipo y factor de sangre')),
                ('antecedentes', models.CharField(max_length=1000)),
                ('medicacion', models.CharField(max_length=1000, verbose_name='Medicación')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.establecimiento')),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.paciente')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.prestacion')),
            ],
        ),
    ]
