# Generated by Django 3.2.6 on 2021-09-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0004_auto_20210908_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miércoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes')], default='Lu', max_length=2, verbose_name='Día de la semana')),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoPrestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_tratamiento', to='odontologia.prestacion')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacionPzaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.piezadental')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_pzadental', to='odontologia.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedicaTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichamedica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.fichamedica')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.tratamiento')),
            ],
        ),
    ]
