# Generated by Django 3.2.6 on 2021-09-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0005_calendarioturnos_fichamedicatratamiento_prestacionpzadental_tratamientoprestacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de usuario'),
        ),
    ]
