from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("localidades", views.localidades_listar, name="localidades"),
    path("nueva_localidad", views.nueva_localidad, name="nueva_localidad"),
    path("modificar_localidad/<int:pk>", views.modificar_localidad, name="modificar_localidad"),
    path("eliminar_localidad/<int:pk>", views.eliminar_localidad, name="eliminar_localidad"),
    path("personas", views.personas_listar, name="personas"),
    path("nueva_persona", views.nueva_persona, name="nueva_persona"),
    path("modificar_persona/<int:pk>", views.modificar_persona, name="modificar_persona"),
    path("eliminar_persona/<int:pk>", views.eliminar_persona, name="eliminar_persona"),
    path("pacientes", views.pacientes_listar, name="pacientes"),
    path("nuevo_paciente", views.nuevo_paciente, name="nuevo_paciente"),
    path("profesionales", views.profesionales_listar, name="profesionales"),
    path("nuevo_profesional", views.nuevo_profesional, name="nuevo_profesional"),
    path("modificar_profesional/<int:pk>", views.modificar_profesional, name="modificar_profesional"),
    path("eliminar_profesional/<int:pk>", views.eliminar_profesional, name="eliminar_profesional"),
    path("modificar_paciente/<int:pk>", views.modificar_paciente, name="modificar_paciente"),
    path("eliminar_paciente/<int:pk>", views.eliminar_paciente, name="eliminar_paciente"),
    path("establecimientos", views.establecimientos_listar, name="establecimientos"),
    path("turnos", views.turnos_listar, name="turnos"),
    path("usuarios", views.usuarios_listar, name="usuarios"),
    path("nuevo_usuario", views.nuevo_usuario, name="nuevo_usuario"),
    path("modificar_usuario<str:pk>", views.modificar_usuario, name="modificar_usuario"),
    path("eliminar_usuario<str:pk>", views.eliminar_usuario, name="eliminar_usuario"),
    path("piezas_dentales", views.pzasdentales_listar, name="piezas_dentales"),
    path("prestaciones", views.prestaciones_listar, name="prestaciones"),
    path("tratamientos", views.tratamientos_listar, name="tratamientos"),
    path("fichas_medicas", views.fichasmedicas_listar, name="fichas_medicas"),
    path("fichamedicatratamiento", views.fichamedicatratamiento_listar, name="fichamedicatratamiento"),
    path("tratamientoprestacion", views.tratamientoprestacion_listar, name="tratamientoprestacion"),
    path("calendarioturnos", views.calendarioturnos_listar, name="calendarioturnos"),
    path("prestacionpiezadental", views.prestaciones_listar, name="prestacionpiezadental"),
    path("turnos", views.turnos_listar, name="turnos"),
    path("nuevo_turno", views.nuevo_turno, name="nuevo_turno"),
    path("modificar_turno<str:pk>", views.modificar_turno, name="modificar_turno"),
    path("eliminar_turno<str:pk>", views.eliminar_turno, name="eliminar_turno"),
]
